# Dynamic Configuration
http:
  routers:
    dashboard:
      rule: (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      plugin:
        icalmiddleware:
          HeaderName:   "Authorization"